apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  name: my-helm-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: my-helm-repository
        namespace: flux-system
      version: 8.9.1
  interval: 0s
  valuesFrom:
  - kind: ConfigMap
    name: my-values
    valuesKey: default-values.yaml
status: {}
